apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "happy-claude-coders.fullname" . }}
  labels:
    {{- include "happy-claude-coders.labels" . | nindent 4 }}
data:
  git-user-name: {{ .Values.git.userName | quote }}
  git-user-email: {{ .Values.git.userEmail | quote }}
  workspace-repos: {{ join " " .Values.workspace.repos | quote }}
